### ISSUE TITLE
set unlimited number of fromDate and endDate

### ISSUE THREAD

**Issue by mohsinalimat** [leverdeterre/CalendarIOS7#13]
In below your code,
how to set unlimited number fromDate and endDate in your code?

NSDateComponents *components = [NSDateComponents new];
    components.month = 1;
    components.day = 1;
    components.year = 1980;
NSDate *fromDate = [[NSDate gregorianCalendar] dateFromComponents:components];
    components.year = 2040;
    components.month = 12;
    components.day = 31;
NSDate *toDate = [[NSDate gregorianCalendar] dateFromComponents:components];

self.calendarVC.calendarManager.beginDate = fromDate;
self.calendarVC.calendarManager.endDate = toDate;

**Comment by bhanubirani** [comment]
I'm running with the similar setup in which I've almost infinite years to scroll i.e from 1970-2040. Is there anyway I can lazy load the layout computation?

I can see the heavy computation in prepareLayout method of CALAgendaMonthCollectionViewLayout class. Please suggest how to further optimize it.
