### ISSUE TITLE
Single month support

### ISSUE THREAD

**Issue by Jules2010** [leverdeterre/CalendarIOS7#15]
I'd like to add a tableview underneath a single data calendar, is this possible?

it would be awesome to have an example project included too, then I could have a play and see if I get to to work with my requirements.

Thanks.

**Comment by leverdeterre** [comment]
Sorry for my very late response.
If you want to use it in a tableView, you have to create your own UItableViewCell and add a AgendaCollectionView subView in your contentView and your tableViewDelegate have to use the AgendaColllectionViewContentSize configure the height of your tableView.
